import numpy as np
from scattering_companion import *
def test01(): assert reduced_mass(1,1)==.5
def test02(): assert np.isclose(reduced_mass(1,1836),1836/1837)
def test03(): assert np.isclose(momentum_transfer(2,0),0)
def test04(): assert np.isclose(momentum_transfer(2,np.pi),4)
def test05(): assert gaussian_born(0)<0
def test06(): assert abs(gaussian_born(10))<abs(gaussian_born(0))
def test07(): assert yukawa_born(0)==-2
def test08(): assert abs(yukawa_born(3))<abs(yukawa_born(0))
def test09(): assert np.isclose(total_cross_section(1,[0]),0)
def test10(): assert np.isclose(total_cross_section(1,[np.pi/2]),4*np.pi)
def test11(): assert abs(optical_residual(1,[.2,.1]))<1e-12
def test12(): assert np.isclose(partial_wave_amplitude(0,1,[.2]),np.exp(.2j)*np.sin(.2))
def test13(): assert np.isclose(abs(effective_range_amplitude(0.0,2)),2)
def test14(): assert np.isclose(abs(effective_range_amplitude(1e-8,2)),2,rtol=1e-6)
def test15(): assert np.isclose(square_well_scattering_length(1,1e-6),0,atol=1e-8)
def test16(): assert np.isclose(abs(breit_wigner_s(0,0,1)),1)
def test17(): assert np.isclose(abs(breit_wigner_s(2,0,1)),1)
def test18(): assert reaction_partial(1,0,1)==0
def test19(): assert reaction_partial(1,0,0)==np.pi
def test20(): assert elastic_partial(1,0,1,0)==0
def test21(): assert np.isclose(elastic_partial(1,0,1,np.pi/2),4*np.pi)
def test22(): assert np.all(np.diff(np.abs(gaussian_born(np.linspace(0,4,10))))<=1e-12)
def test23(): assert np.all(np.isfinite(effective_range_amplitude(np.linspace(.01,1,20),2,.5)))
def test24(): assert np.iscomplexobj(partial_wave_amplitude(np.linspace(0,np.pi,5),1,[.1,.2]))
def test25(): assert total_cross_section(2,[np.pi/2])==np.pi
def test26(): assert np.isclose(forward_amplitude(1,[np.pi/2]).imag,1)
def test27(): assert np.isclose(momentum_transfer(1,np.pi/3),1)
def test28(): assert np.isclose(yukawa_born(0,kappa=2),-.5)
def test29(): assert gaussian_born(0,a=2)==8*gaussian_born(0,a=1)
def test30(): assert np.isclose(reaction_partial(2,1,0),3*np.pi/4)
