import numpy as np
from relativistic_quantum_companion import *
def test01(): assert gamma_factor(0)==1
def test02(): assert np.isclose(gamma_factor(.6),1.25)
def test03(): assert relativistic_energy(0)==1
def test04(): assert np.isclose(relativistic_energy(3,4),5)
def test05(): assert velocity_from_p(0)==0
def test06(): assert velocity_from_p(10)<1
def test07(): assert compton_wavelength()==1
def test08(): assert lower_upper_ratio(0)==0
def test09(): assert 0<lower_upper_ratio(1)<1
def test10(): assert np.isclose(chirality_mix_scale(1,10),.1)
def test11(): assert fine_structure_shift(1,.5)<0
def test12(): assert dirac_coulomb_energy(1,.5)<1
def test13(): assert dirac_coulomb_energy(1,.5)>.99
def test14(): assert np.allclose(boost_current(1,0),[1,0])
def test15(): assert boost_current(1,.6)[0]>1
def test16(): assert helicity_boost_flip(.6,.8)
def test17(): assert not helicity_boost_flip(.8,.6)
def test18(): assert pauli_zeeman(2)==2
def test19(): assert pair_gap()==2
def test20(): assert kg_frequency(0)==1
def test21(): assert kg_frequency(2)>2
def test22(): assert rapidity(0)==0
def test23(): assert np.isclose(beta_from_rapidity(rapidity(.4)),.4)
def test24(): assert np.all(np.diff(relativistic_energy(np.arange(5)))>0)
def test25(): assert np.all(np.diff(velocity_from_p(np.arange(1,6)))>0)
def test26(): assert lower_upper_ratio(100)>.9
def test27(): assert lower_upper_ratio(.01)<.01
def test28(): assert abs(fine_structure_shift(2,1.5))<abs(fine_structure_shift(1,.5))
def test29(): assert dirac_coulomb_energy(2,.5)>dirac_coulomb_energy(1,.5)
def test30(): assert np.isfinite(rapidity(.999))
